services:
  teamspeak:
    image: teamspeak
    restart: always
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: db
      TS3SERVER_DB_USER: root
      TS3SERVER_DB_PASSWORD: example
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
      VIRTUAL_HOST: ts.bigolbear.net
    volumes:
      - "/data/teamspeak3-stack/teamspeak3/var/ts3server:/var/ts3server"
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: teamspeak
    volumes:
      - "/data/teamspeak3-stack/db/var/log:/var/log/mysql"
      - "/data/teamspeak3-stack/db/var/lib:/var/lib/mysql"
      - "/data/teamspeak3-stack/db/etc/mysql:/etc/mysql"
